// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Data;

#nullable disable

namespace Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240725034111_SeedDataToTable")]
    partial class SeedDataToTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Models.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Percentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description for Discount 1",
                            EndDate = new DateTime(2024, 8, 6, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8382),
                            Name = "Discount 1",
                            Percentage = 42.0,
                            StartDate = new DateTime(2024, 7, 24, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8379),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description for Discount 2",
                            EndDate = new DateTime(2024, 8, 13, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8440),
                            Name = "Discount 2",
                            Percentage = 49.0,
                            StartDate = new DateTime(2024, 7, 24, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8438),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description for Discount 3",
                            EndDate = new DateTime(2024, 8, 10, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8487),
                            Name = "Discount 3",
                            Percentage = 17.0,
                            StartDate = new DateTime(2024, 7, 19, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8485),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Description for Discount 4",
                            EndDate = new DateTime(2024, 8, 5, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8534),
                            Name = "Discount 4",
                            Percentage = 18.0,
                            StartDate = new DateTime(2024, 7, 24, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8532),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Description for Discount 5",
                            EndDate = new DateTime(2024, 8, 21, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8580),
                            Name = "Discount 5",
                            Percentage = 46.0,
                            StartDate = new DateTime(2024, 7, 16, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8579),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Description for Discount 6",
                            EndDate = new DateTime(2024, 8, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8631),
                            Name = "Discount 6",
                            Percentage = 16.0,
                            StartDate = new DateTime(2024, 7, 23, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8629),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Description for Discount 7",
                            EndDate = new DateTime(2024, 8, 19, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8678),
                            Name = "Discount 7",
                            Percentage = 2.0,
                            StartDate = new DateTime(2024, 7, 21, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8676),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Description for Discount 8",
                            EndDate = new DateTime(2024, 8, 21, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8725),
                            Name = "Discount 8",
                            Percentage = 28.0,
                            StartDate = new DateTime(2024, 7, 18, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8723),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 9,
                            Description = "Description for Discount 9",
                            EndDate = new DateTime(2024, 8, 16, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8771),
                            Name = "Discount 9",
                            Percentage = 1.0,
                            StartDate = new DateTime(2024, 7, 24, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8770),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Description for Discount 10",
                            EndDate = new DateTime(2024, 8, 5, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8822),
                            Name = "Discount 10",
                            Percentage = 30.0,
                            StartDate = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8820),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 11,
                            Description = "Description for Discount 11",
                            EndDate = new DateTime(2024, 8, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8934),
                            Name = "Discount 11",
                            Percentage = 16.0,
                            StartDate = new DateTime(2024, 7, 19, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8931),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 12,
                            Description = "Description for Discount 12",
                            EndDate = new DateTime(2024, 8, 23, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8982),
                            Name = "Discount 12",
                            Percentage = 46.0,
                            StartDate = new DateTime(2024, 7, 16, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(8980),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 13,
                            Description = "Description for Discount 13",
                            EndDate = new DateTime(2024, 8, 8, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9030),
                            Name = "Discount 13",
                            Percentage = 43.0,
                            StartDate = new DateTime(2024, 7, 18, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9028),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Description for Discount 14",
                            EndDate = new DateTime(2024, 8, 9, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9076),
                            Name = "Discount 14",
                            Percentage = 27.0,
                            StartDate = new DateTime(2024, 7, 20, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9075),
                            Status = (byte)1
                        },
                        new
                        {
                            Id = 15,
                            Description = "Description for Discount 15",
                            EndDate = new DateTime(2024, 8, 7, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9123),
                            Name = "Discount 15",
                            Percentage = 22.0,
                            StartDate = new DateTime(2024, 7, 22, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9121),
                            Status = (byte)1
                        });
                });

            modelBuilder.Entity("Web.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("StoreId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9193),
                            Description = "Description for Product 1",
                            DiscountId = 9,
                            Image = "Image for product 1",
                            Name = "Product 1",
                            Price = 348.54242005712081,
                            StoreId = 6,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 7, 24, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9196)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 28, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9256),
                            Description = "Description for Product 2",
                            DiscountId = 3,
                            Image = "Image for product 2",
                            Name = "Product 2",
                            Price = 45.247897212635756,
                            StoreId = 9,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 6, 26, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9257)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2024, 7, 20, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9309),
                            Description = "Description for Product 3",
                            DiscountId = 15,
                            Image = "Image for product 3",
                            Name = "Product 3",
                            Price = 29.521948594870892,
                            StoreId = 3,
                            SubCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 7, 9, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9311)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 3, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9362),
                            Description = "Description for Product 4",
                            DiscountId = 9,
                            Image = "Image for product 4",
                            Name = "Product 4",
                            Price = 726.67255189117566,
                            StoreId = 6,
                            SubCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 7, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9364)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 7, 21, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9414),
                            Description = "Description for Product 5",
                            DiscountId = 12,
                            Image = "Image for product 5",
                            Name = "Product 5",
                            Price = 785.82630373304016,
                            StoreId = 1,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 7, 21, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9416)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2024, 7, 1, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9472),
                            Description = "Description for Product 6",
                            DiscountId = 13,
                            Image = "Image for product 6",
                            Name = "Product 6",
                            Price = 655.94462031942339,
                            StoreId = 2,
                            SubCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 7, 1, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9474)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 8, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9525),
                            Description = "Description for Product 7",
                            DiscountId = 5,
                            Image = "Image for product 7",
                            Name = "Product 7",
                            Price = 37.203663641703947,
                            StoreId = 13,
                            SubCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 7, 13, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9527)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 29, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9637),
                            Description = "Description for Product 8",
                            DiscountId = 11,
                            Image = "Image for product 8",
                            Name = "Product 8",
                            Price = 395.78751358617774,
                            StoreId = 2,
                            SubCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 7, 23, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9639)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 7, 25, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9696),
                            Description = "Description for Product 9",
                            DiscountId = 8,
                            Image = "Image for product 9",
                            Name = "Product 9",
                            Price = 274.32075513967732,
                            StoreId = 12,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 7, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9698)
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 6, 27, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9755),
                            Description = "Description for Product 10",
                            DiscountId = 7,
                            Image = "Image for product 10",
                            Name = "Product 10",
                            Price = 589.3571084092714,
                            StoreId = 13,
                            SubCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 7, 2, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9757)
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 25, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9808),
                            Description = "Description for Product 11",
                            DiscountId = 6,
                            Image = "Image for product 11",
                            Name = "Product 11",
                            Price = 462.95595240706763,
                            StoreId = 6,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 7, 7, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9810)
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 5, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9861),
                            Description = "Description for Product 12",
                            DiscountId = 7,
                            Image = "Image for product 12",
                            Name = "Product 12",
                            Price = 748.5220655414189,
                            StoreId = 6,
                            SubCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 7, 25, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9863)
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2024, 7, 19, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9914),
                            Description = "Description for Product 13",
                            DiscountId = 14,
                            Image = "Image for product 13",
                            Name = "Product 13",
                            Price = 559.01216819624415,
                            StoreId = 3,
                            SubCategoryId = 3,
                            UpdatedAt = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9916)
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2024, 7, 14, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9967),
                            Description = "Description for Product 14",
                            DiscountId = 7,
                            Image = "Image for product 14",
                            Name = "Product 14",
                            Price = 906.74165197140326,
                            StoreId = 13,
                            SubCategoryId = 2,
                            UpdatedAt = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(9968)
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2024, 7, 14, 10, 41, 10, 812, DateTimeKind.Local).AddTicks(19),
                            Description = "Description for Product 15",
                            DiscountId = 13,
                            Image = "Image for product 15",
                            Name = "Product 15",
                            Price = 199.60368721806509,
                            StoreId = 13,
                            SubCategoryId = 1,
                            UpdatedAt = new DateTime(2024, 7, 14, 10, 41, 10, 812, DateTimeKind.Local).AddTicks(21)
                        });
                });

            modelBuilder.Entity("Web.Models.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("CloseTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeOnly>("OptenTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CloseTime = new TimeOnly(18, 0, 0),
                            Description = "Description for Store 1",
                            Image = "Image for Store 1",
                            Name = "Store 1",
                            OptenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Description for Store 2",
                            Image = "Image for Store 2",
                            Name = "Store 2",
                            OptenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Description for Store 3",
                            Image = "Image for Store 3",
                            Name = "Store 3",
                            OptenTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            CloseTime = new TimeOnly(20, 0, 0),
                            Description = "Description for Store 4",
                            Image = "Image for Store 4",
                            Name = "Store 4",
                            OptenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            CloseTime = new TimeOnly(18, 0, 0),
                            Description = "Description for Store 5",
                            Image = "Image for Store 5",
                            Name = "Store 5",
                            OptenTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            CloseTime = new TimeOnly(21, 0, 0),
                            Description = "Description for Store 6",
                            Image = "Image for Store 6",
                            Name = "Store 6",
                            OptenTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            CloseTime = new TimeOnly(20, 0, 0),
                            Description = "Description for Store 7",
                            Image = "Image for Store 7",
                            Name = "Store 7",
                            OptenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            CloseTime = new TimeOnly(19, 0, 0),
                            Description = "Description for Store 8",
                            Image = "Image for Store 8",
                            Name = "Store 8",
                            OptenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            CloseTime = new TimeOnly(21, 0, 0),
                            Description = "Description for Store 9",
                            Image = "Image for Store 9",
                            Name = "Store 9",
                            OptenTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            CloseTime = new TimeOnly(21, 0, 0),
                            Description = "Description for Store 10",
                            Image = "Image for Store 10",
                            Name = "Store 10",
                            OptenTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            CloseTime = new TimeOnly(18, 0, 0),
                            Description = "Description for Store 11",
                            Image = "Image for Store 11",
                            Name = "Store 11",
                            OptenTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            CloseTime = new TimeOnly(21, 0, 0),
                            Description = "Description for Store 12",
                            Image = "Image for Store 12",
                            Name = "Store 12",
                            OptenTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            CloseTime = new TimeOnly(17, 0, 0),
                            Description = "Description for Store 13",
                            Image = "Image for Store 13",
                            Name = "Store 13",
                            OptenTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            CloseTime = new TimeOnly(19, 0, 0),
                            Description = "Description for Store 14",
                            Image = "Image for Store 14",
                            Name = "Store 14",
                            OptenTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            CloseTime = new TimeOnly(20, 0, 0),
                            Description = "Description for Store 15",
                            Image = "Image for Store 15",
                            Name = "Store 15",
                            OptenTime = new TimeOnly(7, 0, 0)
                        });
                });

            modelBuilder.Entity("Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Avatar = "Avatar for User 1",
                            CreatedAt = new DateTime(2024, 7, 7, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6211),
                            Email = "user111@Example.com",
                            FullName = "User 1",
                            Gender = (byte)0,
                            Password = "111",
                            PhoneNumber = "123164151",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 4, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6232)
                        },
                        new
                        {
                            Id = 2,
                            Avatar = "Avatar for User 2",
                            CreatedAt = new DateTime(2024, 7, 20, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6388),
                            Email = "user222@Example.com",
                            FullName = "User 2",
                            Gender = (byte)0,
                            Password = "222",
                            PhoneNumber = "123264152",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 6, 27, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6391)
                        },
                        new
                        {
                            Id = 3,
                            Avatar = "Avatar for User 3",
                            CreatedAt = new DateTime(2024, 7, 10, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6473),
                            Email = "user333@Example.com",
                            FullName = "User 3",
                            Gender = (byte)0,
                            Password = "333",
                            PhoneNumber = "123364153",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 15, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6475)
                        },
                        new
                        {
                            Id = 4,
                            Avatar = "Avatar for User 4",
                            CreatedAt = new DateTime(2024, 7, 10, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6548),
                            Email = "user444@Example.com",
                            FullName = "User 4",
                            Gender = (byte)1,
                            Password = "444",
                            PhoneNumber = "123464154",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 1, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6550)
                        },
                        new
                        {
                            Id = 5,
                            Avatar = "Avatar for User 5",
                            CreatedAt = new DateTime(2024, 7, 6, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6622),
                            Email = "user555@Example.com",
                            FullName = "User 5",
                            Gender = (byte)0,
                            Password = "555",
                            PhoneNumber = "123564155",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 8, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6624)
                        },
                        new
                        {
                            Id = 6,
                            Avatar = "Avatar for User 6",
                            CreatedAt = new DateTime(2024, 7, 20, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6702),
                            Email = "user666@Example.com",
                            FullName = "User 6",
                            Gender = (byte)1,
                            Password = "666",
                            PhoneNumber = "123664156",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 4, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6703)
                        },
                        new
                        {
                            Id = 7,
                            Avatar = "Avatar for User 7",
                            CreatedAt = new DateTime(2024, 6, 29, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6777),
                            Email = "user777@Example.com",
                            FullName = "User 7",
                            Gender = (byte)1,
                            Password = "777",
                            PhoneNumber = "123764157",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 18, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6778)
                        },
                        new
                        {
                            Id = 8,
                            Avatar = "Avatar for User 8",
                            CreatedAt = new DateTime(2024, 7, 3, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6849),
                            Email = "user888@Example.com",
                            FullName = "User 8",
                            Gender = (byte)0,
                            Password = "888",
                            PhoneNumber = "123864158",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 16, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(6851)
                        },
                        new
                        {
                            Id = 9,
                            Avatar = "Avatar for User 9",
                            CreatedAt = new DateTime(2024, 7, 11, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7021),
                            Email = "user999@Example.com",
                            FullName = "User 9",
                            Gender = (byte)0,
                            Password = "999",
                            PhoneNumber = "123964159",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 6, 28, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7024)
                        },
                        new
                        {
                            Id = 10,
                            Avatar = "Avatar for User 10",
                            CreatedAt = new DateTime(2024, 7, 14, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7105),
                            Email = "user101010@Example.com",
                            FullName = "User 10",
                            Gender = (byte)1,
                            Password = "101010",
                            PhoneNumber = "12310641510",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 7, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7106)
                        },
                        new
                        {
                            Id = 11,
                            Avatar = "Avatar for User 11",
                            CreatedAt = new DateTime(2024, 7, 1, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7178),
                            Email = "user111111@Example.com",
                            FullName = "User 11",
                            Gender = (byte)1,
                            Password = "111111",
                            PhoneNumber = "12311641511",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 6, 28, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7179)
                        },
                        new
                        {
                            Id = 12,
                            Avatar = "Avatar for User 12",
                            CreatedAt = new DateTime(2024, 7, 5, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7251),
                            Email = "user121212@Example.com",
                            FullName = "User 12",
                            Gender = (byte)0,
                            Password = "121212",
                            PhoneNumber = "12312641512",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 14, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7252)
                        },
                        new
                        {
                            Id = 13,
                            Avatar = "Avatar for User 13",
                            CreatedAt = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7323),
                            Email = "user131313@Example.com",
                            FullName = "User 13",
                            Gender = (byte)1,
                            Password = "131313",
                            PhoneNumber = "12313641513",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7324)
                        },
                        new
                        {
                            Id = 14,
                            Avatar = "Avatar for User 14",
                            CreatedAt = new DateTime(2024, 7, 17, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7394),
                            Email = "user141414@Example.com",
                            FullName = "User 14",
                            Gender = (byte)0,
                            Password = "141414",
                            PhoneNumber = "12314641514",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 7, 3, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7395)
                        },
                        new
                        {
                            Id = 15,
                            Avatar = "Avatar for User 15",
                            CreatedAt = new DateTime(2024, 7, 18, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7538),
                            Email = "user151515@Example.com",
                            FullName = "User 15",
                            Gender = (byte)0,
                            Password = "151515",
                            PhoneNumber = "12315641515",
                            RoleId = 1,
                            Status = (byte)1,
                            UpdatedAt = new DateTime(2024, 6, 28, 10, 41, 10, 811, DateTimeKind.Local).AddTicks(7541)
                        });
                });

            modelBuilder.Entity("Web.Models.Product", b =>
                {
                    b.HasOne("Web.Models.Discount", "Discount")
                        .WithMany("Products")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web.Models.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Web.Models.Discount", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Web.Models.Store", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
